import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import React, {useEffect, useState} from "react";
import TinderCard from "react-tinder-card";

export default function Home() {
    const [lastDirection, setLastDirection] = useState()
    const db = [
        {
            name: 'Richard Hendricks',
            url: 'http://place-puppy.com/300x300'
        },
        {
            name: 'Erlich Bachman',
            url: 'http://place-puppy.com/300x301'
        },
        {
            name: 'Monica Hall',
            url: 'http://place-puppy.com/300x302'
        },
        {
            name: 'Jared Dunn',
            url: 'http://place-puppy.com/300x303'
        },
        {
            name: 'Dinesh Chugtai',
            url: 'http://place-puppy.com/300x304'
        }
    ]

    const [TinderCard, setTinderCard] = useState(null);

    useEffect(() => {
        setTinderCard(require("react-tinder-card"));
    }, [])

    const swiped = (direction, nameToDelete) => {
        console.log('removing: ' + nameToDelete)
        setLastDirection(direction)
    }

    const outOfFrame = (name) => {
        console.log(name + ' left the screen!')
    }

    if (!TinderCard) {
        return null; // or a loading indicator
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
          <div className='cardContainer'>
              {db.map((character) =>
                  <TinderCard className='swipe' key={character.name} onSwipe={(dir) => swiped(dir, character.name)} onCardLeftScreen={() => outOfFrame(character.name)}>
                      <div style={{ backgroundImage: 'url(' + character.url + ')' }} className='card'>
                          <h3>{character.name}</h3>
                      </div>
                  </TinderCard>
              )}
          </div>
      </main>
    </>
  )
}